---
- hosts: localhost
  vars:
    a: 5
    b: 10
    name: qasim
    value: alnafi
    list: [1,2,3,4,5,6]  
  tasks:    
  - name: display the arithmetic operators
    debug:
      msg:
       - "{{a + b}}"       
       - "{{a - b}}"       
       - "{{a * b}}"       
       - "{{a / b}}"       
       - "{{a % b}}"
  - name: display the comparison operators
    debug:
      msg:
       - "{{a == b}}"       
       - "{{a != b}}"       
       - "{{a > b}}"       
       - "{{a < b}}"       
       - "{{a <= b}}"       
       - "{{a >= b}}"       
       - "{{ name in 'qasim' }}"       
       - "{{list|max}}"
       - "{{list|min}}"
       - "{{name|upper}}"
       - "{{value|title}}"
  
        
        
