---
- hosts: localhost
  tasks:
  - name: adding header in csv file
    lineinfile:
      path: /home/ansible/os-output.csv
      line: "hostname,ip adsress,,df -h"
      create: yes  
  - name: collectin hostname
    shell: "hostname | tr -d '\\n'"
    register: host_name
  - debug:
      var: host_name.stdout
  - name: gather ip details
    shell: "hostname -I | awk '{print $1}' | tr -d '\n'"
    register: ip_details
  - debug:
      var: ip_details.stdout
  - name: collect the df  details
    shell: "df -h | grep -v 'tmpfs'"
    register: df_details
  - debug:
      var: df_details.stdout_lines
  - name: save the data in csv file
    lineinfile:
      dest: /home/ansible/os-output.csv
      line: "{{ host_name.stdout }},{{ ip_details.stdout }},\"{{ df_details.stdout }}\""  
      delimiter: "\n"
         
