---
- hosts: localhost
  gather_facts: false
  vars_prompt: 
    - name: "qasim"
      prompt: "enter the value"
      private: no  
  tasks:      
  - name: print the prompt value
    debug:
      var: qasim    
